#!/bin/bash

toplevel_directory="$(git rev-parse --show-cdup)"
[ -n "$toplevel_directory" ] && { pushd $toplevel_directory; }
#[ -n "$toplevel_directory" ] && { echo "please run from the toplevel directory"; exit 1; }
if [ -e .git_externals ]
then
find .git_externals -type d -name .git | while read gitdir; do
	dir=$(dirname "$gitdir")
    if [ -d $dir ]; then
	pushd $dir
	echo $dir
	git svn fetch
	git svn rebase
	popd
    fi
done
else
    echo "${0##*/}: none externals need to update "
fi
[ -n "$toplevel_directory" ] && { popd ;}

